name: Daily Data Collection

on:
  schedule:
    # Run at 00:00 UTC every day
    - cron: "0 0 * * *"
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-credentials.json
      BIGQUERY_PROJECT_ID: ${{ secrets.BIGQUERY_PROJECT_ID }}
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Shallow clone for faster checkout

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up GCP credentials
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > gcp-credentials.json

    - name: Run data collection
      run: |
        python -m src.raw_data_collection.main

    - name: Upload logs if failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: collection-logs
        path: |
          *.log
